### ISSUE TITLE
Compatibility certification request for Hibernate Validator

### ISSUE THREAD

**Issue by gunnarmorling** [eclipse-ee4j/beanvalidation-spec#246]
* [x] Organization Name ("Organization") and, if applicable, URL
   Red Hat, Inc., http://redhat.com
* [x] Product Name, Version and download URL (if applicable)
   Hibernate Validator 6.0.17.Final, https://hibernate.org/validator/releases/6.0/
* [x] Specification Name, Version and download URL
   Jakarta Bean Validation 2.0
   https://jakarta.ee/specifications/bean-validation/2.0
* [x] TCK Version, digital SHA-256 fingerprint and download URL
   2.0.5
   05afb564efaa6d893dbeb32fb614d6e2bd18f09cf76244386f3b377d725b14b8
   https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.tar.gz
   b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974
   https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip
* [x] Public URL of TCK Results Summary
   https://developer.jboss.org/wiki/HibernateValidatorJakartaValidationTCKCertificationLog
* [x] Java runtime used to run the implementation
   OpenJDK 64-Bit Server VM (Zulu 8.40.0.25-CA-linux64) (build 25.222-b10, mixed mode)
* [x] Summary of the information for the certification environment, operating system, cloud,
   Fedora release 30 (Thirty)
* [x] By checking this box I acknowledge that I accept the terms of the EFTL.
* [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by bshannon** [comment]
- the third bullet should include a link to the spec download: https://jakarta.ee/specifications/bean-validation/2.0
- the fourth bullet should include the URL of the final signed TCK download: https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.tar.gz
- the TCK results summary both says it's running the 2.0.2 and the 2.0.4.Final version of the TCK, but what you're releasing here is the 2.0.5 version; you need to run against that version and publish those results

**Comment by gunnarmorling** [comment]
> the TCK results summary both says it's running the 2.0.2

Thanks, good catch. Fixed.

> and the 2.0.4.Final version of the TCK

The 2.0.4 here is the previous version of the API signature file. The test run is set up to validate the BV 2.0.2 API against those signatures (representing the BV 2.0.1 API, i.e. last version under the Java EE umbrella) in order to make sure that there are no changes whatsoever to the actual API signatures.

As for the test suite execution, this is running the 2.0.5 TCK tests against HV 6.0.17.

**Comment by bshannon** [comment]
That's very confusing or misleading.  Shouldn't the API signature test version match the
TCK version, or perhaps the spec version?

As far as I can tell the last version of the spec approved by the JCP was "2.0", not "2.0.1".
And of course the version of the Jakarta Bean Validation spec is "2.0".

**Comment by gunnarmorling** [comment]
@bshannon, re-ran the TCK and the signature check against the signature from the 2.0.5 TCK, updated the linked certification log accordingly and also addressed your other remarks regarding links above.

From my PoV, nothing remains to be done from my side apart from adding "certification label" which I still can't do due to lack of permissions (see the discussion on the spec lead mailing list).

**Comment by starksm64** [comment]
Verified SHA256:
Scotts-iMacPro:BV starksm$ shasum -a 256 beanvalidation-tck-dist-2.0.5.tar.gz 
5710e607b1939c54753320d25cb885811ff9b68a51c168c1a0bd37768c9a0a97  beanvalidation-tck-dist-2.0.5.tar.gz

**Comment by gunnarmorling** [comment]
Updated the SHA checksums above as per today's re-release of the TCK tar.gz and zip files.

**Comment by gunnarmorling** [comment]
Updated the SHA checksums above as per today's re-release of the TCK tar.gz and zip files. Also re-ran Hibernate Validator 6.0.17.Final against that new TCK release and updated the linked logs of the certification run.

**Comment by edbratt** [comment]
Is this okay to close? (it's been marked accepted.)
